[2024-08-01 09:27:03,661] {scheduler_job.py:182} INFO - Started process (PID=1234) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:27:03,661] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:27:03,662] {logging_mixin.py:104} INFO - [2024-08-01 09:27:03,662] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:27:03,671] {logging_mixin.py:104} INFO - [2024-08-01 09:27:03,670] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:27:03,672] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:27:03,736] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.077 seconds
[2024-08-01 09:27:34,465] {scheduler_job.py:182} INFO - Started process (PID=1261) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:27:34,466] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:27:34,466] {logging_mixin.py:104} INFO - [2024-08-01 09:27:34,466] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:27:34,475] {logging_mixin.py:104} INFO - [2024-08-01 09:27:34,473] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:27:34,476] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:27:34,551] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.089 seconds
[2024-08-01 09:28:05,107] {scheduler_job.py:182} INFO - Started process (PID=1288) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:28:05,109] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:28:05,109] {logging_mixin.py:104} INFO - [2024-08-01 09:28:05,109] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:28:05,127] {logging_mixin.py:104} INFO - [2024-08-01 09:28:05,124] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:28:05,128] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:28:05,202] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.098 seconds
[2024-08-01 09:28:35,790] {scheduler_job.py:182} INFO - Started process (PID=1315) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:28:35,791] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:28:35,792] {logging_mixin.py:104} INFO - [2024-08-01 09:28:35,792] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:28:35,805] {logging_mixin.py:104} INFO - [2024-08-01 09:28:35,802] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:28:35,806] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:28:35,878] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.092 seconds
[2024-08-01 09:29:06,567] {scheduler_job.py:182} INFO - Started process (PID=1342) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:29:06,568] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:29:06,569] {logging_mixin.py:104} INFO - [2024-08-01 09:29:06,569] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:29:06,581] {logging_mixin.py:104} INFO - [2024-08-01 09:29:06,578] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:29:06,582] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:29:06,653] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.090 seconds
[2024-08-01 09:29:37,243] {scheduler_job.py:182} INFO - Started process (PID=1369) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:29:37,244] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:29:37,245] {logging_mixin.py:104} INFO - [2024-08-01 09:29:37,245] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:29:37,253] {logging_mixin.py:104} INFO - [2024-08-01 09:29:37,251] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:29:37,254] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:29:37,323] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.082 seconds
[2024-08-01 09:30:07,925] {scheduler_job.py:182} INFO - Started process (PID=1396) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:30:07,926] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:30:07,927] {logging_mixin.py:104} INFO - [2024-08-01 09:30:07,927] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:30:07,937] {logging_mixin.py:104} INFO - [2024-08-01 09:30:07,935] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:30:07,939] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:30:08,013] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.091 seconds
[2024-08-01 09:30:38,574] {scheduler_job.py:182} INFO - Started process (PID=1423) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:30:38,575] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:30:38,576] {logging_mixin.py:104} INFO - [2024-08-01 09:30:38,576] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:30:38,588] {logging_mixin.py:104} INFO - [2024-08-01 09:30:38,585] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:30:38,589] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:30:38,661] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.091 seconds
[2024-08-01 09:31:09,257] {scheduler_job.py:182} INFO - Started process (PID=1450) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:31:09,259] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:31:09,260] {logging_mixin.py:104} INFO - [2024-08-01 09:31:09,260] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:31:09,273] {logging_mixin.py:104} INFO - [2024-08-01 09:31:09,270] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:31:09,274] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:31:09,348] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.095 seconds
[2024-08-01 09:31:40,030] {scheduler_job.py:182} INFO - Started process (PID=1477) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:31:40,031] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:31:40,032] {logging_mixin.py:104} INFO - [2024-08-01 09:31:40,032] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:31:40,044] {logging_mixin.py:104} INFO - [2024-08-01 09:31:40,041] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:31:40,045] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:31:40,118] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.091 seconds
[2024-08-01 09:32:11,004] {scheduler_job.py:182} INFO - Started process (PID=1504) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:32:11,005] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:32:11,006] {logging_mixin.py:104} INFO - [2024-08-01 09:32:11,006] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:32:11,018] {logging_mixin.py:104} INFO - [2024-08-01 09:32:11,016] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:32:11,019] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:32:11,091] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.091 seconds
[2024-08-01 09:32:41,552] {scheduler_job.py:182} INFO - Started process (PID=1531) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:32:41,553] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:32:41,554] {logging_mixin.py:104} INFO - [2024-08-01 09:32:41,554] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:32:41,566] {logging_mixin.py:104} INFO - [2024-08-01 09:32:41,563] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:32:41,568] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:32:41,641] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.094 seconds
[2024-08-01 09:33:12,188] {scheduler_job.py:182} INFO - Started process (PID=1558) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:33:12,189] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:33:12,190] {logging_mixin.py:104} INFO - [2024-08-01 09:33:12,190] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:33:12,201] {logging_mixin.py:104} INFO - [2024-08-01 09:33:12,199] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:33:12,201] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:33:12,273] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.089 seconds
[2024-08-01 09:33:42,951] {scheduler_job.py:182} INFO - Started process (PID=1585) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:33:42,952] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:33:42,953] {logging_mixin.py:104} INFO - [2024-08-01 09:33:42,953] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:33:42,968] {logging_mixin.py:104} INFO - [2024-08-01 09:33:42,964] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/test_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_taskflow.py", line 10, in <module>
    tags=["example"],
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2297, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 3004, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2024-08-01 09:33:42,969] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:33:43,041] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.095 seconds
[2024-08-01 09:34:13,636] {scheduler_job.py:182} INFO - Started process (PID=1612) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:34:13,638] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:34:13,639] {logging_mixin.py:104} INFO - [2024-08-01 09:34:13,639] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:34:13,652] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['tutorial']) retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:34:13,726] {logging_mixin.py:104} INFO - [2024-08-01 09:34:13,726] {dag.py:1824} INFO - Sync 1 DAGs
[2024-08-01 09:34:13,742] {logging_mixin.py:104} INFO - [2024-08-01 09:34:13,742] {dag.py:2280} INFO - Setting next_dagrun for tutorial to 2024-08-01 00:00:00+00:00
[2024-08-01 09:34:13,758] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.125 seconds
[2024-08-01 09:34:44,323] {scheduler_job.py:182} INFO - Started process (PID=1639) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:34:44,324] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:34:44,325] {logging_mixin.py:104} INFO - [2024-08-01 09:34:44,325] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:34:44,326] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:34:44,326] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.007 seconds
[2024-08-01 09:35:14,876] {scheduler_job.py:182} INFO - Started process (PID=1666) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:35:14,877] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:35:14,878] {logging_mixin.py:104} INFO - [2024-08-01 09:35:14,878] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:35:14,879] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:35:14,879] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.007 seconds
[2024-08-01 09:35:45,494] {scheduler_job.py:182} INFO - Started process (PID=1693) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:35:45,495] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:35:45,496] {logging_mixin.py:104} INFO - [2024-08-01 09:35:45,496] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:35:45,496] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:35:45,497] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.007 seconds
[2024-08-01 09:36:16,109] {scheduler_job.py:182} INFO - Started process (PID=1720) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:36:16,111] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:36:16,111] {logging_mixin.py:104} INFO - [2024-08-01 09:36:16,111] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:36:16,112] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:36:16,112] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.007 seconds
[2024-08-01 09:36:46,743] {scheduler_job.py:182} INFO - Started process (PID=1747) to work on /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:36:46,745] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/test_taskflow.py for tasks to queue
[2024-08-01 09:36:46,746] {logging_mixin.py:104} INFO - [2024-08-01 09:36:46,746] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:36:46,746] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/test_taskflow.py
[2024-08-01 09:36:46,747] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/test_taskflow.py took 0.008 seconds
